public enum GeneratedOperationNames {
  public static let all: [String] = [
    "listDiscover", "createDiscover", "getDiscover", "retryDiscover",
    "getDiscoverCapabilities", "resolveDiscoverGame", "listDiscoverAnalysisBatches",
    "createDiscoverAnalysisBatch", "getDiscoverAnalysisBatch",
    "listJobs",
    "createAnalysisJob",
    "retryAnalysisJob",
    "getAnalysisJob",
    "listMatches",
    "createMatch",
    "getMatch",
    "retryMatch",
    "listOutreachCampaigns",
    "getOutreachCampaign",
    "getOutreachDelivery",
    "resendOutreachDelivery",
    "createOutreachSendBatch",
    "previewOutreachSendBatch",
    "getOutreachSMTPSettings",
    "updateOutreachSMTPSettings",
    "testOutreachSMTPConnection",
    "sendOutreachSMTPTestEmail",
    "listOutreachTemplates",
    "createOutreachTemplate",
    "deleteOutreachTemplate",
    "getOutreachTemplate",
    "updateOutreachTemplate",
    "setDefaultOutreachTemplate",
    "duplicateOutreachTemplate",
    "previewOutreachTemplate",
    "listCreatorProfiles",
    "listCreatorProfilePage",
    "updateCreatorManual",
    "listGameProfiles",
    "rejectUnknownProfileType",
    "getProfile",
    "getProfileEdit",
    "updateProfileEdit",
    "setProfileFavorite",
    "validateSession",
    "getConnectionStatus",
    "testConnection",
    "replaceConnectionSecret",
    "getReanalysisSettings",
    "updateReanalysisSettings",
    "checkLiveness",
    "checkReadiness",
    "showCreatorResponseConfirmation",
    "confirmCreatorResponse",
  ]
}
