import { contextBridge, ipcRenderer } from 'electron';
import type { DesktopBridge } from '../shared/bridge';

const bridge: DesktopBridge = {
  analysis: Object.freeze({
    steamImport: (input: Parameters<DesktopBridge['analysis']['steamImport']>[0]) => ipcRenderer.invoke('analysis:steamImport', input),
    bindYouTube: (input: Parameters<DesktopBridge['analysis']['bindYouTube']>[0]) => ipcRenderer.invoke('analysis:bindYouTube', input),
    create: (input: Parameters<DesktopBridge['analysis']['create']>[0]) => ipcRenderer.invoke('analysis:create', input),
    detail: (input: Parameters<DesktopBridge['analysis']['detail']>[0]) => ipcRenderer.invoke('analysis:detail', input),
    changed: (input: Parameters<DesktopBridge['analysis']['changed']>[0]) => ipcRenderer.invoke('analysis:changed', input),
    retry: (input: Parameters<DesktopBridge['analysis']['retry']>[0]) => ipcRenderer.invoke('analysis:retry', input),
    resume: (input: Parameters<DesktopBridge['analysis']['resume']>[0]) => ipcRenderer.invoke('analysis:resume', input),
  }),
  collaboration: {
    list: input => ipcRenderer.invoke('collaboration:list', input),
    detail: input => ipcRenderer.invoke('collaboration:detail', input),
    creatorHistory: input => ipcRenderer.invoke('collaboration:creatorHistory', input),
    update: input => ipcRenderer.invoke('collaboration:update', input),
    respond: input => ipcRenderer.invoke('collaboration:respond', input),
  },
  sending: {
    qualify: input => ipcRenderer.invoke('sending:qualify', input),
    send: input => ipcRenderer.invoke('sending:send', input),
    batches: input => ipcRenderer.invoke('sending:batches', input),
    batch: id => ipcRenderer.invoke('sending:batch', id),
    retry: input => ipcRenderer.invoke('sending:retry', input),
    resolve: input => ipcRenderer.invoke('sending:resolve', input),
  },
  drafts: {
    templates: input => ipcRenderer.invoke('drafts:templates', input),
    template: id => ipcRenderer.invoke('drafts:template', id),
    registerCanonical: input => ipcRenderer.invoke('drafts:register-canonical', input),
    createTemplate: input => ipcRenderer.invoke('drafts:create-template', input),
    compositions: input => ipcRenderer.invoke('drafts:compositions', input),
    composition: id => ipcRenderer.invoke('drafts:composition', id),
    createComposition: input => ipcRenderer.invoke('drafts:create-composition', input),
    edit: input => ipcRenderer.invoke('drafts:edit', input),
    refresh: input => ipcRenderer.invoke('drafts:refresh', input),
    retry: input => ipcRenderer.invoke('drafts:retry', input),
    senderFacts: input => ipcRenderer.invoke('drafts:sender-facts', input),
  },
  outreach: {
    selections:input=>ipcRenderer.invoke('outreach:selections',input),
    selection:input=>ipcRenderer.invoke('outreach:selection',input),
    add:input=>ipcRenderer.invoke('outreach:add',input),
    bulk:input=>ipcRenderer.invoke('outreach:bulk',input),
    update:input=>ipcRenderer.invoke('outreach:update',input),
    cancel:input=>ipcRenderer.invoke('outreach:cancel',input),
    batches:input=>ipcRenderer.invoke('outreach:batches',input),
    batch:input=>ipcRenderer.invoke('outreach:batch',input),
    freeze:input=>ipcRenderer.invoke('outreach:freeze',input),
  },
  savedSets: {
    list:input=>ipcRenderer.invoke('saved-sets:list',input),
    detail:id=>ipcRenderer.invoke('saved-sets:detail',id),
    results:input=>ipcRenderer.invoke('saved-sets:results',input),
    create:input=>ipcRenderer.invoke('saved-sets:create',input),
  },
  match: {
    activities:input=>ipcRenderer.invoke('match:activities',input),
    createActivity:input=>ipcRenderer.invoke('match:create-activity',input),
    activity:id=>ipcRenderer.invoke('match:activity',id),
    plans:input=>ipcRenderer.invoke('match:plans',input),
    createPlan:input=>ipcRenderer.invoke('match:create-plan',input),
    plan:id=>ipcRenderer.invoke('match:plan',id),
    retryPlan:input=>ipcRenderer.invoke('match:retry-plan',input),
    query:id=>ipcRenderer.invoke('match:query',id),
    candidates:input=>ipcRenderer.invoke('match:candidates',input),
    stop:input=>ipcRenderer.invoke('match:stop',input),
    continueDiscovery:input=>ipcRenderer.invoke('match:continue',input),
    evaluations:input=>ipcRenderer.invoke('match:evaluations',input),
    evaluate:input=>ipcRenderer.invoke('match:evaluate',input),
    evaluation:id=>ipcRenderer.invoke('match:evaluation',id),
    evaluationResults:input=>ipcRenderer.invoke('match:evaluation-results',input),
    retryEvaluation:input=>ipcRenderer.invoke('match:retry-evaluation',input),
  },
  creators: {
    list: input => ipcRenderer.invoke('creators:list',input),
    detail: id => ipcRenderer.invoke('creators:detail',id),
    create: input => ipcRenderer.invoke('creators:create',input),
    update: input => ipcRenderer.invoke('creators:update',input),
    rebind: input => ipcRenderer.invoke('creators:rebind',input),
    createContact: input => ipcRenderer.invoke('creators:create-contact',input),
    updateContact: input => ipcRenderer.invoke('creators:update-contact',input),
    works: input => ipcRenderer.invoke('creators:works',input),
    createWork: input => ipcRenderer.invoke('creators:create-work',input),
    updateWork: input => ipcRenderer.invoke('creators:update-work',input),
  },
  settings: {
    collection: () => ipcRenderer.invoke('settings:collection'),
    setCollection: input => ipcRenderer.invoke('settings:set-collection', input),
    connection: service => ipcRenderer.invoke('settings:connection', service),
    replaceConnection: input => ipcRenderer.invoke('settings:replace-connection', input),
    testConnection: service => ipcRenderer.invoke('settings:test-connection', service),
    reanalysis: () => ipcRenderer.invoke('settings:reanalysis'),
    saveReanalysis: input => ipcRenderer.invoke('settings:save-reanalysis', input),
    smtp: () => ipcRenderer.invoke('settings:smtp'),
    saveSMTP: input => ipcRenderer.invoke('settings:save-smtp', input),
    testSMTP: () => ipcRenderer.invoke('settings:test-smtp'),
    sendTestEmail: input => ipcRenderer.invoke('settings:send-test-email', input),
  },
  preferences: {
    read: () => ipcRenderer.invoke('preferences:read'),
    update: input => ipcRenderer.invoke('preferences:update', input),
    restoreAppearance: () => ipcRenderer.invoke('preferences:restore-appearance'),
  },
  updates: {
    status: () => ipcRenderer.invoke('updates:status'),
    check: () => ipcRenderer.invoke('updates:check'),
  },
  connection: {
    status: () => ipcRenderer.invoke('connection:status'),
    save: input => ipcRenderer.invoke('connection:save', input),
    test: () => ipcRenderer.invoke('connection:test'),
    clear: () => ipcRenderer.invoke('connection:clear'),
  },
  library: {
    list: input => ipcRenderer.invoke('library:list', input),
    detail: input => ipcRenderer.invoke('library:detail', input),
  },
  games: {
    list: input => ipcRenderer.invoke('games:list', input),
    detail: id => ipcRenderer.invoke('games:detail', id),
    create: input => ipcRenderer.invoke('games:create', input),
    update: input => ipcRenderer.invoke('games:update', input),
  },
  openExternal: url => ipcRenderer.invoke('system:open-external', url),
};
contextBridge.exposeInMainWorld('desktop', bridge);
