// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {act,cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {afterEach,expect,it,vi} from 'vitest';
import type {DesktopBridge} from '../src/shared/bridge';
import type {NavigationGuard} from '../src/shared/games';
import {AnalyzeProvider,useAnalyze} from '../src/renderer/components/analyze/AnalyzeProvider';
afterEach(()=>{cleanup();vi.useRealTimers();});
const target={target_type:'creator' as const,url:'https://x.com/i/user/900000001',mode:'reanalyze' as const,title:'Pixel Harbor',profileId:'creator-1'};
const job=(overrides:Record<string,unknown>={})=>({outcome:'job',id:'job-1',target_type:'creator',canonical_target_id:'x:900000001',canonical_url:target.url,mode:'reanalyze',status:'queued',stage:null,completed_units:0,total_units:0,retryable:false,error:null,correlation_id:null,profile_id:null,created_at:'2026-09-09T00:00:00Z',updated_at:'2026-09-09T00:00:00Z',started_at:null,completed_at:null,waiting_reason:null,resume_available:false,...overrides});
const ok=(data:unknown)=>({ok:true,data});
function apiMock(){return {analysis:{create:vi.fn(async()=>ok(job())),detail:vi.fn(async()=>ok(job())),retry:vi.fn(async()=>ok(job({id:'job-2'}))),resume:vi.fn(async()=>ok(job())),changed:vi.fn(async()=>ok({items:[],cursor:'cursor',has_more:false,affected_profile_ids:[]}))}} as unknown as DesktopBridge;}
function Controls(){const a=useAnalyze();return <><button onClick={()=>a.request(target)}>Analyze creator</button><button onClick={a.showTasks}>Tasks</button><button onClick={a.credentialsChanged}>Change connection</button><input aria-label="Unrelated editor"/></>;}
function setup(api=apiMock()){const open=vi.fn(),repair=vi.fn(),settings=vi.fn();render(<AnalyzeProvider api={api} onOpenProfile={open} onConnectionRepair={repair} onCollectionSettings={settings}><Controls/></AnalyzeProvider>);return {api,open,repair,settings,user:userEvent.setup()};}
it('requires explicit confirmation, retains task through close and only opens a completed profile on request',async()=>{
 const {api,user,open}=setup();vi.mocked(api.analysis.create).mockResolvedValue(ok(job({status:'succeeded',stage:'finalizing',completed_units:3,total_units:3,profile_id:'creator-1',completed_at:'2026-09-09T00:01:00Z'})) as never);
 await user.click(screen.getByText('Analyze creator'));expect(api.analysis.create).not.toHaveBeenCalled();expect(screen.getByText(/provider.*cost/i)).toBeVisible();await user.click(screen.getByRole('button',{name:'Analyze now'}));await screen.findByText('Ready');expect(open).not.toHaveBeenCalled();await user.click(screen.getByLabelText('Close analysis tasks'));await user.click(screen.getByText('Tasks'));await user.click(screen.getByRole('button',{name:'View profile'}));expect(open).toHaveBeenCalledWith({kind:'creators',id:'creator-1'});
});
it('replays exactly one frozen uncertain intent and cannot bypass it with another target',async()=>{
 const {api,user}=setup();vi.mocked(api.analysis.create).mockRejectedValueOnce(new Error('lost'));
 await user.click(screen.getByText('Analyze creator'));await user.click(screen.getByRole('button',{name:'Analyze now'}));await screen.findByText('Request not confirmed');const original=vi.mocked(api.analysis.create).mock.calls[0][0];await user.click(screen.getByLabelText('Close analysis tasks'));await user.click(screen.getByText('Analyze creator'));expect(screen.queryByRole('button',{name:'Analyze now'})).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Retry original request'}));await screen.findByText('Queued');expect(api.analysis.create).toHaveBeenCalledTimes(2);expect(vi.mocked(api.analysis.create).mock.calls[1][0]).toEqual(original);expect(Object.isFrozen(original)).toBe(true);
});
it('fences an in-flight write after credentials change and stops replay',async()=>{
 const {api,user}=setup();let resolve!:(v:unknown)=>void;vi.mocked(api.analysis.create).mockImplementation(()=>new Promise(r=>{resolve=r as typeof resolve;}));await user.click(screen.getByText('Analyze creator'));await user.click(screen.getByRole('button',{name:'Analyze now'}));await user.click(screen.getByText('Change connection'));await act(async()=>resolve(ok(job())));expect(screen.getByText('Connection changed')).toBeVisible();expect(screen.queryByRole('button',{name:'Retry original request'})).not.toBeInTheDocument();expect(screen.queryByText('Queued')).not.toBeInTheDocument();
});
it('shows collection waiting instead of progress, with explicit resume only when offered',async()=>{
 const {api,user,settings}=setup();vi.mocked(api.analysis.create).mockResolvedValue(ok(job({waiting_reason:'collection_disabled'})) as never);await user.click(screen.getByText('Analyze creator'));await user.click(screen.getByRole('button',{name:'Analyze now'}));await screen.findByText('Collection paused');expect(screen.queryByRole('button',{name:'Resume analysis'})).not.toBeInTheDocument();await user.click(screen.getByRole('button',{name:'Collection settings'}));expect(settings).toHaveBeenCalledOnce();expect(api.analysis.resume).not.toHaveBeenCalled();
});
it('labels an existing profile honestly and returns keyboard focus on Escape',async()=>{
 const {api,user,open}=setup();vi.mocked(api.analysis.create).mockResolvedValue(ok({outcome:'existing_profile',existing_profile_id:'creator-1',target_type:'creator',canonical_target_id:'x:900000001',canonical_url:target.url}) as never);await user.click(screen.getByText('Analyze creator'));await user.click(screen.getByRole('button',{name:'Analyze now'}));await screen.findByText('Already in your library');expect(screen.queryByText('Ready')).not.toBeInTheDocument();expect(open).not.toHaveBeenCalled();await user.keyboard('{Escape}');expect(screen.getByText('Analyze creator')).toHaveFocus();
});
it('offers an empty state and lazy history without dispatching jobs',async()=>{
 const {api,user}=setup();expect(api.analysis.changed).not.toHaveBeenCalled();await user.click(screen.getByText('Tasks'));await screen.findByText('No analysis tasks');expect(api.analysis.create).not.toHaveBeenCalled();expect(api.analysis.changed).toHaveBeenCalledOnce();
});
it('does not lock workspace settings just because read-only task history was opened',async()=>{
 const api=apiMock(),register=vi.fn<(guard:NavigationGuard|null)=>void>(),user=userEvent.setup();render(<AnalyzeProvider api={api} onNavigationGuardChange={register}><Controls/></AnalyzeProvider>);expect(register).toHaveBeenLastCalledWith(null);await user.click(screen.getByText('Tasks'));await screen.findByText('No analysis tasks');expect(register).toHaveBeenLastCalledWith(null);await user.click(screen.getByText('Change connection'));expect(register).toHaveBeenLastCalledWith(null);
});
it('requires explicit retry for a failed task and uses a new key rather than replaying the create',async()=>{
 const {api,user}=setup();vi.mocked(api.analysis.create).mockResolvedValue(ok(job({status:'failed',retryable:true,error:{code:'x_unavailable',message:'Analysis is temporarily unavailable. Please retry.'},completed_at:'2026-09-09T00:01:00Z'})) as never);await user.click(screen.getByText('Analyze creator'));await user.click(screen.getByRole('button',{name:'Analyze now'}));await screen.findByText('Analysis failed');expect(api.analysis.retry).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'Retry analysis'}));await screen.findByText('Queued');expect(api.analysis.retry).toHaveBeenCalledOnce();expect(vi.mocked(api.analysis.retry).mock.calls[0][0].idempotencyKey).not.toBe(vi.mocked(api.analysis.create).mock.calls[0][0].idempotencyKey);
});
it('locks a retry when returned task belongs to a different target',async()=>{
 const {api,user}=setup();vi.mocked(api.analysis.create).mockResolvedValue(ok(job({status:'failed',retryable:true,error:{code:'x_unavailable',message:'Try again'}})) as never);vi.mocked(api.analysis.retry).mockResolvedValue(ok(job({id:'job-2',canonical_target_id:'x:other',canonical_url:'https://x.com/i/user/other'})) as never);await user.click(screen.getByText('Analyze creator'));await user.click(screen.getByRole('button',{name:'Analyze now'}));await user.click(await screen.findByRole('button',{name:'Retry analysis'}));await screen.findByText('Request not confirmed');expect(screen.queryByText('Queued')).not.toBeInTheDocument();
});
it('resumes only after a refreshed server state explicitly permits it',async()=>{
 const {api,user}=setup();vi.mocked(api.analysis.create).mockResolvedValue(ok(job({waiting_reason:'collection_disabled'})) as never);vi.mocked(api.analysis.detail).mockResolvedValue(ok(job({waiting_reason:'explicit_resume_required',resume_available:true,updated_at:'2026-09-09T00:01:00Z'})) as never);vi.mocked(api.analysis.resume).mockResolvedValue(ok(job({updated_at:'2026-09-09T00:02:00Z'})) as never);await user.click(screen.getByText('Analyze creator'));await user.click(screen.getByRole('button',{name:'Analyze now'}));await user.click(await screen.findByRole('button',{name:'Refresh status'}));await screen.findByText('Ready to resume');expect(api.analysis.resume).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'Resume analysis'}));await screen.findByText('Queued');expect(api.analysis.resume).toHaveBeenCalledOnce();
});
it('does not replay after the 24-hour retention window',async()=>{
 const {api,user}=setup();vi.mocked(api.analysis.create).mockRejectedValueOnce(new Error('lost'));await user.click(screen.getByText('Analyze creator'));await user.click(screen.getByRole('button',{name:'Analyze now'}));await screen.findByText('Request not confirmed');const now=Date.now();const date=vi.spyOn(Date,'now').mockReturnValue(now+86_400_001);await user.click(screen.getByLabelText('Close analysis tasks'));await user.click(screen.getByText('Tasks'));expect(screen.queryByRole('button',{name:'Retry original request'})).not.toBeInTheDocument();expect(api.analysis.create).toHaveBeenCalledOnce();date.mockRestore();
});
it('serializes status polling and does not steal focus when background analysis finishes',async()=>{
 vi.useFakeTimers();const api=apiMock(),open=vi.fn();let resolve!:(v:unknown)=>void;vi.mocked(api.analysis.detail).mockImplementation(()=>new Promise(r=>{resolve=r as typeof resolve;}));render(<AnalyzeProvider api={api} onOpenProfile={open}><Controls/></AnalyzeProvider>);fireEvent.click(screen.getByText('Analyze creator'));await act(async()=>fireEvent.click(screen.getByRole('button',{name:'Analyze now'})));await act(async()=>vi.advanceTimersByTime(2000));expect(api.analysis.detail).toHaveBeenCalledOnce();await act(async()=>vi.advanceTimersByTime(8000));expect(api.analysis.detail).toHaveBeenCalledOnce();screen.getByLabelText('Unrelated editor').focus();await act(async()=>resolve(ok(job({status:'succeeded',profile_id:'creator-1',updated_at:'2026-09-09T00:03:00Z'}))));expect(screen.getByText('Ready')).toBeVisible();expect(screen.getByLabelText('Unrelated editor')).toHaveFocus();expect(open).not.toHaveBeenCalled();
});
it('does not let an old history response replace a just accepted task',async()=>{
 const {api,user}=setup();let resolve!:(v:unknown)=>void;vi.mocked(api.analysis.changed).mockImplementationOnce(()=>new Promise(r=>{resolve=r as typeof resolve;}));await user.click(screen.getByText('Tasks'));await user.click(screen.getByLabelText('Close analysis tasks'));await user.click(screen.getByText('Analyze creator'));vi.mocked(api.analysis.create).mockResolvedValue(ok(job({status:'succeeded',profile_id:'creator-1'})) as never);await user.click(screen.getByRole('button',{name:'Analyze now'}));await screen.findByText('Ready');await act(async()=>resolve(ok({items:[{...job(),kind:'analysis',resource_id:'job-1'}],cursor:'cursor',has_more:false,affected_profile_ids:[]})));expect(screen.getByText('Ready')).toBeVisible();expect(screen.queryByText('Queued')).not.toBeInTheDocument();
});
it.each(['expired','fenced'] as const)('retains an acknowledged %s request without claiming success or automatically resubmitting',async(reason)=>{
 const {api,user}=setup();vi.mocked(api.analysis.create).mockRejectedValueOnce(new Error('lost'));await user.click(screen.getByText('Analyze creator'));await user.click(screen.getByRole('button',{name:'Analyze now'}));await screen.findByText('Request not confirmed');const original=vi.mocked(api.analysis.create).mock.calls[0][0];let clock:ReturnType<typeof vi.spyOn>|undefined;
 if(reason==='fenced')await user.click(screen.getByText('Change connection'));else{clock=vi.spyOn(Date,'now').mockReturnValue(Date.now()+86_400_001);await user.click(screen.getByLabelText('Close analysis tasks'));await user.click(screen.getByText('Tasks'));}
 await user.click(screen.getByRole('button',{name:'Keep unresolved request'}));expect(screen.getByText(/may still complete.*not a cancellation/i)).toBeVisible();expect(api.analysis.create).toHaveBeenCalledOnce();await user.click(screen.getByRole('button',{name:'Acknowledge and keep record'}));expect(screen.getByText('Unconfirmed request')).toBeVisible();expect(screen.queryByText('Ready')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Analyze now'})).not.toBeInTheDocument();await user.click(screen.getByText('Original request'));expect(screen.getByText(/"idempotencyKey"/)).toHaveTextContent(original.idempotencyKey);expect(screen.getByText(/"idempotencyKey"/)).toHaveTextContent(target.url);expect(api.analysis.create).toHaveBeenCalledOnce();
 if(reason==='fenced')expect(screen.queryByRole('button',{name:'View known profile'})).not.toBeInTheDocument();else expect(screen.getByRole('button',{name:'View known profile'})).toBeVisible();
 await user.click(screen.getByLabelText('Close analysis tasks'));await user.click(screen.getByText('Analyze creator'));expect(api.analysis.create).toHaveBeenCalledOnce();await user.click(screen.getByRole('button',{name:'Analyze now'}));await screen.findByText('Queued');expect(vi.mocked(api.analysis.create).mock.calls[1][0].idempotencyKey).not.toBe(original.idempotencyKey);expect(screen.getByText('Unconfirmed request')).toBeVisible();clock?.mockRestore();
});
it('retains a source request as an immutable read-only record across a credential detour',async()=>{
 const api=apiMock(),request={url:'https://store.steampowered.com/app/123',idempotencyKey:'keep-original-source-key'},register=vi.fn();function Source(){const a=useAnalyze();return <button onClick={()=>a.retainUnconfirmed({title:'Steam import',request,startedAt:1234,profile:{kind:'games',id:'game-1'}})}>Keep source request</button>;}
 render(<AnalyzeProvider api={api} onNavigationGuardChange={register}><Controls/><Source/></AnalyzeProvider>);const user=userEvent.setup();await user.click(screen.getByText('Keep source request'));request.url='changed';await user.click(screen.getByText('Tasks'));await user.click(screen.getByText('Original request'));expect(screen.getByText(/keep-original-source-key/)).toHaveTextContent('/app/123');await user.click(screen.getByText('Change connection'));expect(screen.getByText('Unconfirmed request')).toBeVisible();expect(screen.getByText(/keep-original-source-key/)).toHaveTextContent('/app/123');expect(register.mock.calls.at(-1)?.[0]?.recovery).toBeDefined();expect(api.analysis.create).not.toHaveBeenCalled();
});
