// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import { StrictMode } from 'react';
import { act, cleanup, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, expect, it, vi } from 'vitest';
import type { DesktopBridge, Result } from '../src/shared/bridge';
import type { CreatorPage } from '../src/shared/creators';
import { CreatorLibrary } from '../src/renderer/components/creators/CreatorLibrary';
import { LibraryView } from '../src/renderer/components/LibraryView';
import type { NavigationGuard } from '../src/shared/games';
import { creatorAPIMock } from './creator-api-mock';
import { creatorFixture } from './creator-fixtures';
const ok = <T,>(data:T):Result<T> => ({ok:true,data});
const page = (name='Creator fixture',offset=0,total=1):CreatorPage => ({items:[creatorFixture(name)],offset,total,limit:50});
const apiMock = () => ({creators:creatorAPIMock(),openExternal:vi.fn(async()=>ok(undefined))} as unknown as DesktopBridge);
afterEach(cleanup);
it('submits search explicitly with platform, language and saved filters using offset pages', async()=>{
  const api=apiMock(); vi.mocked(api.creators.list).mockImplementation(async input=>ok(page('Creator fixture',input.offset,51)));
  render(<CreatorLibrary api={api} active/>); const user=userEvent.setup();
  await screen.findByRole('button',{name:'Open Creator fixture'});
  await user.type(screen.getByRole('searchbox',{name:'Search creators'}),'cozy');
  expect(api.creators.list).toHaveBeenCalledOnce();
  await user.click(screen.getByRole('button',{name:'Platforms: Any'}));
  await user.click(within(screen.getByRole('dialog',{name:'Platforms'})).getByRole('checkbox',{name:'Twitch'}));
  await user.click(within(screen.getByRole('dialog',{name:'Platforms'})).getByRole('button',{name:'Apply'}));
  await user.click(screen.getByRole('button',{name:'Languages: Any'}));
  await user.click(within(screen.getByRole('dialog',{name:'Languages'})).getByRole('checkbox',{name:'English · en'}));
  await user.click(within(screen.getByRole('dialog',{name:'Languages'})).getByRole('button',{name:'Apply'}));
  await user.click(screen.getByRole('checkbox',{name:'Saved only'}));
  await user.click(screen.getByRole('button',{name:'Search'}));
  await waitFor(()=>expect(api.creators.list).toHaveBeenLastCalledWith({query:'cozy',platforms:['twitch'],languages:['en'],sort:'relevance',onlyCollection:true,offset:0,limit:50}));
  await user.click(screen.getByRole('button',{name:'Next page'}));
  await waitFor(()=>expect(api.creators.list).toHaveBeenLastCalledWith({query:'cozy',platforms:['twitch'],languages:['en'],sort:'relevance',onlyCollection:true,offset:50,limit:50}));
});
it('retains a valid page on failure and retries the exact failed input under StrictMode',async()=>{
  const api=apiMock(); vi.mocked(api.creators.list).mockImplementation(async input=>input.offset?{ok:false,error:{code:'network_error',message:'Page interrupted',retryable:true}}:ok(page('First',0,51)));
  render(<StrictMode><CreatorLibrary api={api} active/></StrictMode>);const user=userEvent.setup();
  await screen.findByRole('button',{name:'Open First'});await user.click(screen.getByRole('button',{name:'Next page'}));
  await screen.findByText('Page interrupted');expect(screen.getByText('1–1 of 51')).toBeVisible();
  expect(screen.getByRole('button',{name:'Open First'})).toBeVisible();
  const failed=vi.mocked(api.creators.list).mock.lastCall![0];
  await user.type(screen.getByRole('searchbox',{name:'Search creators'}),'unsubmitted');
  vi.mocked(api.creators.list).mockResolvedValueOnce(ok(page('Second',50,51)));
  await user.click(screen.getByRole('button',{name:'Try again'}));await screen.findByRole('button',{name:'Open Second'});
  expect(api.creators.list).toHaveBeenLastCalledWith(failed);
});
it('ignores stale reads, keeps zero distinct from unknown and offers creation when empty',async()=>{
  let finish!:(value:Result<CreatorPage>)=>void;const pending=new Promise<Result<CreatorPage>>(resolve=>{finish=resolve;});
  const api=apiMock();vi.mocked(api.creators.list).mockImplementation(async input=>input.query==='old'?pending:ok({items:input.query==='new'?[{...creatorFixture('Zero'),follower_count:0},creatorFixture('Unknown','another')]:[],total:input.query==='new'?2:0,offset:0,limit:50}));
  render(<CreatorLibrary api={api} active/>);const user=userEvent.setup();await screen.findByRole('heading',{name:'No creators yet'});
  expect(screen.getByRole('button',{name:'New creator'})).toBeEnabled();
  const search=screen.getByRole('searchbox');await user.type(search,'old{Enter}');await user.clear(search);await user.type(search,'new{Enter}');
  await screen.findByRole('button',{name:'Open Zero'});expect(screen.getByText('0 followers')).toBeVisible();expect(screen.getByText('Followers unknown')).toBeVisible();
  await act(async()=>finish(ok(page('Stale'))));expect(screen.queryByRole('button',{name:'Open Stale'})).not.toBeInTheDocument();
});
it('preserves selection, section and list filters across outer visibility changes without extra reads',async()=>{
  const api=apiMock();const {rerender}=render(<CreatorLibrary api={api} active/>);const user=userEvent.setup();
  await screen.findByRole('button',{name:'Open Creator fixture'});await user.type(screen.getByRole('searchbox'),'saved{Enter}');
  await user.click(await screen.findByRole('button',{name:'Open Creator fixture'}));await screen.findByRole('heading',{name:'Creator fixture'});
  await user.click(screen.getByRole('tab',{name:'Emails'}));
  rerender(<CreatorLibrary api={api} active={false}/>);rerender(<CreatorLibrary api={api} active/>);
  expect(screen.getByRole('tab',{name:'Emails'})).toHaveAttribute('aria-selected','true');
  expect(api.creators.detail).toHaveBeenCalledOnce();expect(api.creators.list).toHaveBeenCalledTimes(2);
  await user.click(screen.getByRole('button',{name:'Back to creators'}));expect(screen.getByRole('searchbox')).toHaveValue('saved');
  await waitFor(()=>expect(screen.getByRole('button',{name:'Open Creator fixture'})).toHaveFocus());
});
it('reconciles a saved creator and clamps a filtered page without losing filters or detail',async()=>{
  const api=apiMock();const initial={...creatorFixture(),favorite:true};let changed=false;
  vi.mocked(api.creators.list).mockImplementation(async input=>ok(changed?page('Remaining',0,1):{items:[initial],offset:input.offset??0,total:51,limit:50}));
  vi.mocked(api.creators.detail).mockImplementation(async()=>ok({...initial,favorite:!changed,revision:changed?4:3}));
  vi.mocked(api.creators.update).mockImplementation(async()=>{changed=true;return ok({...initial,favorite:false,revision:4});});
  render(<CreatorLibrary api={api} active/>);const user=userEvent.setup();
  await screen.findByRole('button',{name:'Open Creator fixture'});await user.type(screen.getByRole('searchbox'),'cozy{Enter}');
  await user.click(screen.getByRole('button',{name:'Platforms: Any'}));
  await user.click(within(screen.getByRole('dialog',{name:'Platforms'})).getByRole('checkbox',{name:'YouTube'}));
  await user.click(within(screen.getByRole('dialog',{name:'Platforms'})).getByRole('button',{name:'Apply'}));
  await user.click(screen.getByRole('checkbox',{name:'Saved only'}));await user.click(screen.getByRole('button',{name:'Next page'}));
  await screen.findByText('51–51 of 51');await user.click(screen.getByRole('button',{name:'Open Creator fixture'}));
  await user.click(await screen.findByRole('button',{name:'Edit profile'}));await user.click(screen.getByRole('checkbox',{name:'Saved'}));
  await user.click(screen.getByRole('button',{name:'Save changes'}));await screen.findByRole('button',{name:'Edit profile'});
  expect(api.creators.update).toHaveBeenCalledWith({id:initial.id,data:{expected_revision:3,favorite:false}});
  await waitFor(()=>expect(api.creators.list).toHaveBeenLastCalledWith(expect.objectContaining({query:'cozy',platforms:['youtube'],sort:'relevance',onlyCollection:true,offset:0})));
  expect(screen.getByRole('status')).toHaveTextContent('Saved');await user.click(screen.getByRole('button',{name:'Back to creators'}));
  expect(screen.getByRole('searchbox')).toHaveValue('cozy');expect(screen.getByRole('checkbox',{name:'Saved only'})).toBeChecked();
  expect(screen.getByRole('button',{name:'Open Remaining'})).toBeVisible();expect(screen.getByText('1–1 of 1')).toBeVisible();
});
it('keeps a save successful when list refresh fails and returns email edits to Emails',async()=>{
  const api=apiMock();const changed={...creatorFixture(),revision:4,contacts:[{...creatorFixture().contacts[0],email:'changed@example.com'}]};
  vi.mocked(api.creators.list).mockResolvedValueOnce(ok(page())).mockResolvedValue({ok:false,error:{code:'network_error',message:'Refresh unavailable',retryable:true}});
  vi.mocked(api.creators.detail).mockResolvedValueOnce(ok(creatorFixture())).mockResolvedValue(ok(changed));
  vi.mocked(api.creators.updateContact).mockResolvedValue(ok(changed));
  render(<CreatorLibrary api={api} active/>);const user=userEvent.setup();
  await user.click(await screen.findByRole('button',{name:'Open Creator fixture'}));await user.click(await screen.findByRole('tab',{name:'Emails'}));
  await user.click(screen.getByRole('button',{name:'Edit creator@example.com'}));
  const email=screen.getByRole('textbox',{name:'Email'});await user.clear(email);await user.type(email,'changed@example.com');
  await user.click(screen.getByRole('button',{name:'Save changes'}));await screen.findByRole('tab',{name:'Emails'});
  expect(screen.getByRole('tab',{name:'Emails'})).toHaveAttribute('aria-selected','true');expect(screen.getByText('changed@example.com')).toBeVisible();
  expect(screen.getByRole('status')).toHaveTextContent('Saved');await user.click(screen.getByRole('button',{name:'Back to creators'}));
  expect(screen.getByRole('alert')).toHaveTextContent('Refresh unavailable');expect(api.creators.updateContact).toHaveBeenCalledOnce();
});
it('uses only the selected Library guard for tabs and workspace navigation',async()=>{
  const api=apiMock();api.games={list:vi.fn(async()=>ok({items:[],total:0,offset:0,limit:24})),detail:vi.fn(),create:vi.fn(),update:vi.fn()};
  let guard:NavigationGuard|null=null;const onGuard=vi.fn((value:NavigationGuard|null)=>{guard=value;});
  render(<LibraryView api={api} active onNavigationGuardChange={onGuard}/>);const user=userEvent.setup();
  await user.click(await screen.findByRole('button',{name:'New creator'}));await user.type(screen.getByRole('textbox',{name:'Name'}),'Preserve draft');
  const leave=vi.fn();await act(async()=>{guard?.(leave);});expect(screen.getByRole('dialog')).toBeVisible();await user.keyboard('{Escape}');expect(leave).not.toHaveBeenCalled();
  await user.click(screen.getByRole('tab',{name:'Games'}));expect(screen.getByRole('tab',{name:'Creators'})).toHaveAttribute('aria-selected','true');
  await user.click(screen.getByRole('button',{name:'Discard changes'}));await screen.findByRole('heading',{name:'No games yet'});
  expect(onGuard).toHaveBeenLastCalledWith(null);screen.getByRole('tab',{name:'Games'}).focus();await user.keyboard('{Home}');
  expect(screen.getByRole('tab',{name:'Creators'})).toHaveFocus();expect(api.creators.list).toHaveBeenCalledOnce();
});
it('retains reload-required state when leaving for Games after an accepted save',async()=>{
  const api=apiMock();api.games={list:vi.fn(async()=>ok({items:[],total:0,offset:0,limit:24})),detail:vi.fn(),create:vi.fn(),update:vi.fn()};
  const latest={...creatorFixture('Current saved creator'),revision:4};const user=userEvent.setup();let guard:NavigationGuard|null=null;
  vi.mocked(api.creators.detail).mockResolvedValueOnce(ok(creatorFixture())).mockResolvedValueOnce({ok:false,error:{code:'network_error',message:'Readback unavailable',retryable:true}}).mockResolvedValueOnce(ok(latest));
  vi.mocked(api.creators.update).mockResolvedValueOnce(ok(latest));
  render(<LibraryView api={api} active onNavigationGuardChange={value=>{guard=value;}}/>);
  await user.click(await screen.findByRole('button',{name:'Open Creator fixture'}));await user.click(await screen.findByRole('button',{name:'Edit profile'}));
  await user.clear(screen.getByLabelText('Name'));await user.type(screen.getByLabelText('Name'),'Current saved creator');await user.click(screen.getByRole('button',{name:'Save changes'}));
  await screen.findByText('Readback unavailable');
  await user.click(screen.getByRole('tab',{name:'Games'}));await user.click(screen.getByRole('button',{name:'Leave without reloading'}));
  await screen.findByRole('heading',{name:'No games yet'});await user.click(screen.getByRole('tab',{name:'Creators'}));
  expect(screen.getByRole('heading',{name:'Save received'})).toBeVisible();
  expect(screen.queryByRole('button',{name:'Edit profile'})).not.toBeInTheDocument();
  expect(screen.queryByRole('button',{name:'Save changes'})).not.toBeInTheDocument();
  expect(guard).not.toBeNull();expect(api.creators.detail).toHaveBeenCalledTimes(2);
  await user.click(screen.getByRole('button',{name:'Retry current record'}));
  expect(await screen.findByRole('heading',{name:'Current saved creator'})).toBeVisible();
  expect(screen.getByRole('button',{name:'Edit profile'})).toBeEnabled();
  expect(api.creators.update).toHaveBeenCalledTimes(1);expect(api.creators.create).not.toHaveBeenCalled();expect(api.creators.detail).toHaveBeenCalledTimes(3);
});
it('requires current readback on internal Back instead of restoring the pre-save creator',async()=>{
  const api=apiMock();const latest={...creatorFixture('Current saved creator'),revision:4};const user=userEvent.setup();
  vi.mocked(api.creators.detail).mockResolvedValueOnce(ok(creatorFixture())).mockResolvedValueOnce({ok:false,error:{code:'network_error',message:'Readback unavailable',retryable:true}}).mockResolvedValueOnce(ok(latest));
  vi.mocked(api.creators.update).mockResolvedValueOnce(ok(latest));
  render(<CreatorLibrary api={api} active/>);
  await user.click(await screen.findByRole('button',{name:'Open Creator fixture'}));await user.click(await screen.findByRole('button',{name:'Edit profile'}));
  await user.clear(screen.getByLabelText('Name'));await user.type(screen.getByLabelText('Name'),'Current saved creator');await user.click(screen.getByRole('button',{name:'Save changes'}));
  await screen.findByText('Readback unavailable');await user.click(screen.getByRole('button',{name:'Back to creator'}));
  let dialog=within(screen.getByRole('dialog'));
  expect(dialog.queryByRole('button',{name:'Leave without reloading'})).not.toBeInTheDocument();
  expect(dialog.queryByRole('button',{name:'Discard changes'})).not.toBeInTheDocument();
  await user.click(dialog.getByRole('button',{name:'Stay here'}));
  expect(screen.getByRole('heading',{name:'Save received'})).toBeVisible();
  await user.click(screen.getByRole('button',{name:'Back to creator'}));dialog=within(screen.getByRole('dialog'));
  await user.click(dialog.getByRole('button',{name:'Retry current record'}));
  expect(await screen.findByRole('heading',{name:'Current saved creator'})).toBeVisible();
  expect(screen.queryByRole('heading',{name:'Creator fixture'})).not.toBeInTheDocument();
  expect(screen.getByRole('button',{name:'Edit profile'})).toBeEnabled();
  expect(api.creators.update).toHaveBeenCalledTimes(1);expect(api.creators.detail).toHaveBeenCalledTimes(3);
});
it('returns internal Save and leave to the readback detail instead of the pre-save detail',async()=>{
  const api=apiMock();const latest={...creatorFixture('Current saved creator'),revision:4};const user=userEvent.setup();
  vi.mocked(api.creators.detail).mockResolvedValueOnce(ok(creatorFixture())).mockResolvedValueOnce(ok(latest));
  vi.mocked(api.creators.update).mockResolvedValueOnce(ok(latest));
  render(<CreatorLibrary api={api} active/>);
  await user.click(await screen.findByRole('button',{name:'Open Creator fixture'}));await user.click(await screen.findByRole('button',{name:'Edit profile'}));
  await user.clear(screen.getByLabelText('Name'));await user.type(screen.getByLabelText('Name'),'Current saved creator');await user.click(screen.getByRole('button',{name:'Back to creator'}));
  await user.click(screen.getByRole('button',{name:'Save and leave'}));
  expect(await screen.findByRole('heading',{name:'Current saved creator'})).toBeVisible();
  expect(screen.queryByRole('heading',{name:'Creator fixture'})).not.toBeInTheDocument();
  expect(api.creators.update).toHaveBeenCalledTimes(1);expect(api.creators.detail).toHaveBeenCalledTimes(2);
});
it('labels source platforms and manual discovery truthfully',async()=>{
  const api=apiMock();const twitch=creatorFixture('Manual Twitch'),instagram=creatorFixture('Manual Instagram','instagram-record');
  vi.mocked(api.creators.list).mockResolvedValue(ok({items:[{...twitch,source_identity:{...twitch.source_identity,platform:'twitch'}},{...instagram,source_identity:{...instagram.source_identity,platform:'instagram'}}],total:2,offset:0,limit:50}));
  render(<CreatorLibrary api={api} active/>);
  const row=await screen.findByRole('button',{name:'Open Manual Twitch'});expect(within(row).getByText('Twitch')).toBeVisible();expect(within(row).getByText('Manual · discovery unavailable')).toBeVisible();
  expect(within(screen.getByRole('button',{name:'Open Manual Instagram'})).getByText('Instagram')).toBeVisible();
  expect(screen.queryByRole('button',{name:/fetch|analy[sz]e/i})).not.toBeInTheDocument();
});
it('restores separate tab scroll positions and selected list row focus',async()=>{
  const api=apiMock();api.games={list:vi.fn(async()=>ok({items:[],total:0,offset:0,limit:24})),detail:vi.fn(),create:vi.fn(),update:vi.fn()};
  const {container}=render(<div className="main-scroll"><LibraryView api={api} active/></div>);const scroller=container.querySelector<HTMLElement>('.main-scroll')!;const user=userEvent.setup();
  await screen.findByRole('button',{name:'Open Creator fixture'});scroller.scrollTop=230;
  await user.click(screen.getByRole('tab',{name:'Games'}));await screen.findByRole('heading',{name:'No games yet'});await waitFor(()=>expect(scroller.scrollTop).toBe(0));scroller.scrollTop=90;
  await user.click(screen.getByRole('tab',{name:'Creators'}));await waitFor(()=>expect(scroller.scrollTop).toBe(230));
  await user.click(screen.getByRole('button',{name:'Open Creator fixture'}));await screen.findByRole('heading',{name:'Creator fixture'});expect(scroller.scrollTop).toBe(0);
  await user.click(screen.getByRole('button',{name:'Back to creators'}));await waitFor(()=>expect(scroller.scrollTop).toBe(230));expect(screen.getByRole('button',{name:'Open Creator fixture'})).toHaveFocus();
  await user.click(screen.getByRole('tab',{name:'Games'}));await waitFor(()=>expect(scroller.scrollTop).toBe(90));
});
