import { createHash } from 'node:crypto';
import type { Delivery, QualifiedMember, Qualification, SendBatch, SendingIdentity } from '../src/shared/sending';
import { draftFixture, draftIds, draftValues } from './drafts-fixtures';
export const sendingIds = { ...draftIds, batch: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', delivery: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb' };
export const sendingIdentity: SendingIdentity = { address: 'synthetic-sender@example.test', name: 'Synthetic sender', reply_to: null };
const fragments = ['<p>Hi ', ', I follow ', ' and enjoyed ', '. I liked how you ', '</p>'];
const subject = 'Synthetic frozen invitation';
const fixedHash = createHash('sha256').update(subject + '\n' + fragments.join('<slot/>')).digest('hex');
const html = fragments[0] + Object.values(draftValues).map((v, i) => `<span background-color="rgba(255,246,122,0.8)">${v}</span>${fragments[i + 1]}`).join('');
export function qualifiedMemberFixture(patch: Partial<QualifiedMember> = {}): QualifiedMember { return { draft_id: draftIds.draft, recipient_snapshot_id: draftIds.recipient, status: 'eligible', missing_fields: [], exclusion_reason: null, recipient_email: 'synthetic-recipient@example.test', subject, html, text: `Hi ${draftValues.firstName}, I follow ${draftValues.channelName} and enjoyed ${draftValues.reference}. I liked how you ${draftValues.observation}`, values: { ...draftValues }, slot_sources: structuredClone(draftFixture().slot_sources), template_version_id: draftIds.template, fixed_hash: fixedHash, revision: 1, context_token: 'a'.repeat(64), sender_facts: { following: true, enjoyed: true, liked: true, at: '2026-09-08T00:00:00Z', fingerprint: 'b'.repeat(64) }, identity: { platform: 'youtube', account_id: 'synthetic-account', revision: 0 }, blocking_delivery_id: null, ...patch }; }
export function qualificationFixture(patch: Partial<Qualification> = {}): Qualification { return { composition_id: draftIds.composition, activity_id: draftIds.activity, qualification_token: 'c'.repeat(64), sending_account_token: 'd'.repeat(64), total_count: 1, eligible_count: 1, repair_count: 0, excluded_count: 0, sender: { ...sendingIdentity }, members: [qualifiedMemberFixture()], send_ready: true, ...patch }; }
export function deliveryFixture(patch: Partial<Delivery> = {}): Delivery { return { id: sendingIds.delivery, send_batch_id: sendingIds.batch, draft_id: draftIds.draft, recipient_snapshot_id: draftIds.recipient, snapshot: { ...qualifiedMemberFixture(), status: 'eligible', sender: { ...sendingIdentity }, sending_account_token: 'd'.repeat(64) }, state: 'queued', attempt: 0, retryable: false, error_code: null, sending_at: null, sent_at: null, failed_at: null, resolution: {}, ...patch }; }
export function sendBatchFixture(patch: Partial<SendBatch> = {}): SendBatch { return { id: sendingIds.batch, activity_id: draftIds.activity, composition_id: draftIds.composition, created_at: '2026-09-08T00:00:00Z', qualification: qualificationFixture(), deliveries: [deliveryFixture()], ...patch }; }
