import type * as DTO from '../shared/analyze';
import { decodeDetail as decodeGame } from './game-client';
import { decodeCreator } from './creator-validation';
import { decodeChanged, decodeJob, decodeOutcome, exact, fail, identifier, integer, keys, object, target } from './analyze-validation';
import { analysisWriteUnknown, isAnalysisWrite, validateAnalysisRequest, type AnalysisRequest } from './analyze-transport';
export { analysisWriteUnknown, isAnalysisWrite, validateAnalysisRequest }; export type { AnalysisRequest };
type Input<K extends keyof DTO.AnalysisAPI> = Parameters<DTO.AnalysisAPI[K]>[0];
export class AnalysisClient {
  constructor(private readonly request: (input: AnalysisRequest) => Promise<unknown>) {}
  private async perform<T>(input: AnalysisRequest, decode: (v: unknown) => T): Promise<T> { const r = validateAnalysisRequest(input), value = await this.request(r); try { return decode(value); } catch (e) { throw isAnalysisWrite(r) ? analysisWriteUnknown() : e; } }
  async steamImport(value: Input<'steamImport'>) { const r = object(value, 'input'); keys(r, ['url','gameId','expectedRevision','idempotencyKey'], 'input'); if (Object.hasOwn(r,'gameId') !== Object.hasOwn(r,'expectedRevision')) fail('input'); const body = { url: r.url, ...(Object.hasOwn(r,'gameId') ? { game_id: r.gameId, expected_revision: r.expectedRevision } : {}) }; return this.perform({ method:'POST', path:'/api/v2/library/games/steam-import', body, idempotencyKey:r.idempotencyKey as string }, v => { const row = decodeGame(v, r.gameId as string | undefined), t = target('game', r.url, 'input'); if (row.source_identity.steam_app_id !== t.id || row.source_identity.canonical_url !== t.url || r.expectedRevision !== undefined && row.revision !== (r.expectedRevision as number) + 1) fail('response'); return row; }); }
  async bindYouTube(value: Input<'bindYouTube'>) { const r = exact(value, ['creatorId','url','expectedRevision','idempotencyKey'], 'input'), id = identifier(r.creatorId,'input'); return this.perform({method:'POST',path:`/api/v2/library/creators/${id}/youtube-binding`,body:{url:r.url,expected_revision:r.expectedRevision},idempotencyKey:r.idempotencyKey as string}, v => { const row = decodeCreator(v,id), t = target('creator', row.source_identity.canonical_url,'response'), requested = target('creator', r.url,'input'); if (row.platform !== 'youtube' || !t.resolved || t.id.startsWith('x:') || t.id !== row.source_identity.account_id || requested.resolved && t.id !== requested.id || row.revision !== (r.expectedRevision as number) + 1) fail('response'); return row; }); }
  async create(value: Input<'create'>) { const r = exact(value,['target_type','url','mode','idempotencyKey'],'input'); return this.perform({method:'POST',path:'/api/v1/jobs/analysis',body:{target_type:r.target_type,url:r.url,mode:r.mode},idempotencyKey:r.idempotencyKey as string},v => { const row = decodeOutcome(v), t = target(r.target_type,r.url,'input'); if (row.target_type !== r.target_type || (t.resolved ? row.canonical_target_id !== t.id : !row.canonical_target_id.startsWith('UC'))) fail('response'); return row; }); }
  async detail(value: Input<'detail'>) { const r = exact(value,['jobId'],'input'), id = identifier(r.jobId,'input'); return this.perform({method:'GET',path:`/api/v1/jobs/${id}`},v => decodeJob(v,id)); }
  async changed(value: Input<'changed'>) { const r = object(value,'input'); keys(r,['cursor','limit'],'input'); const limit = integer(r.limit ?? 100,'input',1,200); return this.perform({method:'GET',path:'/api/v1/jobs',query:{limit:String(limit),...(Object.hasOwn(r,'cursor') ? {changed_after:r.cursor as string} : {})}},v => decodeChanged(v,limit)); }
  private async action(value: Input<'retry'>, action: 'retry'|'resume') { const r = exact(value,['jobId','idempotencyKey'],'input'), id = identifier(r.jobId,'input'); return this.perform({method:'POST',path:`/api/v1/jobs/analysis/${id}/${action}`,...(action === 'retry' ? {body:{}} : {}),idempotencyKey:r.idempotencyKey as string},v => decodeJob(v,action === 'resume' ? id : undefined)); }
  retry(v: Input<'retry'>) { return this.action(v,'retry'); }
  resume(v: Input<'resume'>) { return this.action(v,'resume'); }
}
