import type * as DTO from '../shared/sending';
import { checkExclusions, decodeBatch, decodeDelivery, decodePage, decodeQualification, exact, fail, identifier, integer } from './sending-validation';
import { isSendingWrite, sendingWriteUnknown, validateSendingRequest, type SendingRequest } from './sending-transport';
export { isSendingWrite, sendingWriteUnknown, validateSendingRequest };
export type { SendingRequest };
type Input<K extends keyof DTO.SendingAPI> = Parameters<DTO.SendingAPI[K]>[0];
export class SendingClient {
  constructor(private readonly request: (input: SendingRequest) => Promise<unknown>) {}
  private async sendRequest<T>(request: SendingRequest, decode: (v: unknown) => T): Promise<T> { const valid = validateSendingRequest(request), result = await this.request(valid); try { return decode(result); } catch (error) { throw isSendingWrite(valid) ? sendingWriteUnknown() : error; } }
  async qualify(value: Input<'qualify'>): Promise<DTO.Qualification> { const r = exact(value, ['compositionId', 'data'], 'input'), id = identifier(r.compositionId, 'input'), data = r.data as DTO.QualificationRequest; return this.sendRequest({ method: 'POST', path: `/api/v2/outreach/compositions/${id}/qualification`, body: data as unknown as Record<string, unknown> }, v => { const q = decodeQualification(v, id); checkExclusions(q, data.excluded); return q; }); }
  async send(value: Input<'send'>): Promise<DTO.SendBatch> { const r = exact(value, ['compositionId', 'data', 'idempotencyKey'], 'input'), id = identifier(r.compositionId, 'input'), data = r.data as DTO.FinalSendRequest; return this.sendRequest({ method: 'POST', path: `/api/v2/outreach/compositions/${id}/send-batches`, body: data as unknown as Record<string, unknown>, idempotencyKey: r.idempotencyKey as string }, v => { const batch = decodeBatch(v, undefined, id); if (batch.qualification.qualification_token !== data.qualification_token) fail('response'); checkExclusions(batch.qualification, data.excluded); return batch; }); }
  async batches(value: Input<'batches'>): Promise<DTO.SendBatchPage> { const r = Object.assign({}, value); keysPage(r); const id = identifier(r.activityId, 'input'), offset = integer(r.offset ?? 0, 'input'), limit = integer(r.limit ?? 50, 'input', 1, 100); return this.sendRequest({ method: 'GET', path: `/api/v2/activities/${id}/send-batches`, query: { offset: String(offset), limit: String(limit) } }, v => decodePage(v, id, offset, limit)); }
  async batch(id: string): Promise<DTO.SendBatch> { identifier(id, 'input'); return this.sendRequest({ method: 'GET', path: `/api/v2/outreach/send-batches/${id}` }, v => decodeBatch(v, id)); }
  async retry(value: Input<'retry'>): Promise<DTO.Delivery> { const r = exact(value, ['id', 'data'], 'input'), id = identifier(r.id, 'input'), data = r.data as DTO.DeliveryRetry; return this.sendRequest({ method: 'POST', path: `/api/v2/outreach/deliveries/${id}/retry`, body: data as unknown as Record<string, unknown> }, v => { const d = decodeDelivery(v, id); if (d.attempt !== data.expected_attempt || d.state !== 'queued') fail('response'); return d; }); }
  async resolve(value: Input<'resolve'>): Promise<DTO.Delivery> { const r = exact(value, ['id', 'data'], 'input'), id = identifier(r.id, 'input'), data = r.data as DTO.DeliveryResolution; return this.sendRequest({ method: 'POST', path: `/api/v2/outreach/deliveries/${id}/resolve`, body: data as unknown as Record<string, unknown> }, v => { const d = decodeDelivery(v, id); if (d.attempt !== data.expected_attempt || d.state !== (data.outcome === 'sent' ? 'sent' : 'failed') || d.resolution.outcome !== data.outcome || d.resolution.source_note !== data.source_note.trim() || d.resolution.attempt !== data.expected_attempt) fail('response'); return d; }); }
}
function keysPage(v: Record<string, unknown>) { if (Object.keys(v).some(k => !['activityId', 'offset', 'limit'].includes(k))) fail('input'); }
