import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import type {PublicError} from '../../../shared/bridge';
import type {AnalysisJob,ExistingProfile} from '../../../shared/analyze';
import {canReplayAnalysis,type AnalyzeOperation,type AnalyzeTarget,type AnalyzeTask,type RetainedAnalysisRequest} from './AnalyzeProvider';
interface Props {
 visible:boolean;target:AnalyzeTarget|null;tasks:AnalyzeTask[];retained:RetainedAnalysisRequest[];workspaceGeneration:number;existing:ExistingProfile|null;operation:AnalyzeOperation|null;error:PublicError|null;readErrors:Record<string,string>;historyBusy:boolean;historyError:string|null;hasMore:boolean;onKeepUnresolved:()=>void;
 onClose:()=>void;onAnalyze:()=>void;onDismissTarget:()=>void;onReplay:()=>void;onRetry:(job:AnalysisJob)=>void;onResume:(job:AnalysisJob)=>void;onRefresh:(id:string)=>void;onHistory:()=>void;onConnectionRepair?:()=>void;onCollectionSettings?:()=>void;onOpenProfile?:(profile:{kind:'games'|'creators';id:string})=>void;
}
function status(job:AnalysisJob){if(job.waiting_reason==='collection_disabled')return 'Collection paused';if(job.waiting_reason==='explicit_resume_required')return 'Ready to resume';if(job.status==='succeeded')return 'Ready';if(job.status==='failed')return 'Analysis failed';if(job.status==='queued')return 'Queued';return {fetching_data:'Collecting sources',analyzing:'Analyzing',finalizing:'Saving profile'}[job.stage??'fetching_data'];}
export function AnalyzeDrawer(p:Props){
 const heading=useRef<HTMLHeadingElement>(null),focusWasInside=useRef(false);
 const [acknowledging,setAcknowledging]=useState(false);
 useEffect(()=>setAcknowledging(false),[p.operation?.attempt,p.visible]);
 useEffect(()=>{if(p.visible)heading.current?.focus();},[p.visible]);
 useLayoutEffect(()=>{if(p.visible&&focusWasInside.current&&document.activeElement===document.body)heading.current?.focus();},[p.visible,p.target,p.operation,p.existing]);
 const locked=!!p.operation;
 return <aside className="analysis-drawer" role="dialog" aria-modal="false" aria-labelledby="analysis-drawer-title" hidden={!p.visible} onFocusCapture={()=>{focusWasInside.current=true;}} onBlurCapture={event=>{if(event.relatedTarget&&!event.currentTarget.contains(event.relatedTarget as Node))focusWasInside.current=false;}} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();p.onClose();}}}>
  <header className="analysis-drawer-header"><h2 id="analysis-drawer-title" tabIndex={-1} ref={heading}>Analysis</h2><button type="button" aria-label="Close analysis tasks" onClick={p.onClose}>×</button></header>
  <div className="analysis-drawer-content">
   {p.target&&!locked?<section className="analysis-confirm" aria-label="Confirm analysis"><h3>{p.target.title}</h3><p className="analysis-url">{p.target.url}</p><p className="analysis-cost">Uses your connected providers; model costs may apply.</p><div className="analysis-actions"><button className="primary" onClick={p.onAnalyze}>Analyze now</button><button onClick={p.onDismissTarget}>Not now</button></div></section>:null}
   {p.operation?<section className="analysis-operation" aria-live="polite"><h3>{p.operation.attempt.fenced?'Connection changed':p.operation.phase==='running'?'Submitting request':'Request not confirmed'}</h3>{p.operation.phase==='uncertain'?<><p>{p.operation.error?.message}</p><div className="analysis-actions">{canReplayAnalysis(p.operation.attempt)?<button onClick={p.onReplay}>Retry original request</button>:<p>{p.operation.attempt.fenced?'Return to the original workspace to check this request.':'Retry window expired. Check task history before starting another request.'}</p>}{p.onConnectionRepair?<button onClick={p.onConnectionRepair}>Connection settings</button>:null}<button onClick={p.onHistory}>Check task history</button></div></>:<p>Closing this panel does not cancel the request.</p>}</section>:null}
   {p.operation?.phase==='uncertain'&&!canReplayAnalysis(p.operation.attempt)?<section aria-label="Keep unresolved analysis">{acknowledging?<><p>The original request may still complete. This is not a cancellation or a confirmed result. Its input and key stay here for review; a new request could duplicate work and cost.</p><p>Records remain in this window until it closes.</p><div className="analysis-actions"><button onClick={p.onKeepUnresolved}>Acknowledge and keep record</button><button onClick={()=>setAcknowledging(false)}>Back</button></div></>:<button onClick={()=>setAcknowledging(true)}>Keep unresolved request</button>}</section>:null}
   {p.error?<div role="alert"><p>{p.error.message}</p>{p.onConnectionRepair&&['workspace_key_invalid','not_connected','secure_storage_unavailable','connection_changed'].includes(p.error.code)?<button onClick={p.onConnectionRepair}>Connection settings</button>:null}{p.onCollectionSettings&&p.error.code.includes('collection')?<button onClick={p.onCollectionSettings}>Collection settings</button>:null}</div>:null}
   {p.existing?<section><h3>Already in your library</h3><p className="analysis-url">{p.existing.canonical_url}</p>{p.onOpenProfile?<button onClick={()=>p.onOpenProfile?.({kind:p.existing!.target_type==='game'?'games':'creators',id:p.existing!.existing_profile_id})}>View profile</button>:null}</section>:null}
   {p.tasks.map(({job,title})=><article className="analysis-task" key={job.id} aria-label={`Analysis: ${title}`}><header><h3>{title}</h3><span className={`analysis-status analysis-status-${job.waiting_reason?'waiting':job.status}`}>{status(job)}</span></header><p className="analysis-url">{job.canonical_url}</p>
    {job.status==='running'&&!job.waiting_reason?<div className="analysis-stages" aria-label={`Stage: ${status(job)}`}>{['fetching_data','analyzing','finalizing'].map((stage,i)=><span key={stage} className={stage===job.stage?'current':''}>{i+1}</span>)}</div>:null}
    {job.error?<p role="alert">{job.error.message}</p>:null}{p.readErrors[job.id]?<p role="alert">{p.readErrors[job.id]}</p>:null}
    <div className="analysis-actions">{job.status==='succeeded'&&job.profile_id&&p.onOpenProfile?<button className="primary" onClick={()=>p.onOpenProfile?.({kind:job.target_type==='game'?'games':'creators',id:job.profile_id!})}>View profile</button>:null}
     {job.status==='failed'&&job.retryable?<button disabled={locked} onClick={()=>p.onRetry(job)}>Retry analysis</button>:null}
     {job.resume_available?<button disabled={locked} onClick={()=>p.onResume(job)}>Resume analysis</button>:null}
     {job.waiting_reason&&p.onCollectionSettings?<button onClick={p.onCollectionSettings}>Collection settings</button>:null}
     {job.status!=='succeeded'?<button disabled={locked} onClick={()=>p.onRefresh(job.id)}>Refresh status</button>:null}
    </div><details><summary>Task details</summary><dl><dt>Task</dt><dd>{job.id}</dd><dt>Updated</dt><dd>{new Date(job.updated_at).toLocaleString()}</dd>{job.correlation_id?<><dt>Support ID</dt><dd>{job.correlation_id}</dd></>:null}</dl></details>
   </article>)}
   {p.retained.map(record=><article className="analysis-task" key={record.id} aria-label={`Unconfirmed: ${record.title}`}><header><h3>{record.title}</h3><span className="analysis-status analysis-status-waiting">Unconfirmed request</span></header><p>Not cancelled or confirmed. Check the original workspace.</p><details><summary>Original request</summary><dl><dt>Started</dt><dd>{new Date(record.startedAt).toISOString()}</dd></dl><pre className="analysis-request-record">{record.requestText}</pre></details>{record.profile&&record.workspaceGeneration===p.workspaceGeneration&&p.onOpenProfile?<button onClick={()=>p.onOpenProfile?.(record.profile!)}>View known profile</button>:null}</article>)}
   {!p.target&&!p.operation&&!p.existing&&!p.tasks.length&&!p.retained.length&&!p.historyBusy&&!p.historyError?<p className="analysis-empty">No analysis tasks</p>:null}
   {p.historyBusy?<p role="status">Loading tasks…</p>:null}{p.historyError?<div role="alert"><p>{p.historyError}</p><button onClick={p.onHistory}>Retry task history</button></div>:null}{p.hasMore?<button disabled={p.historyBusy} onClick={p.onHistory}>Load more tasks</button>:null}
  </div>
 </aside>;
}
