import {test,expect,type BrowserContext,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createServer,type Server} from 'node:http';
import type {AddressInfo} from 'node:net';
import path from 'node:path';
import {publicResult} from '../src/main/transport';
import {analyzeFixture,requireCheck,ROOT,ORIGIN,canonical,events,eventCounts,sha} from './analyze-fixture';
test.use({trace:'off',screenshot:'off',video:'off'});
test('Analyze built renderer imports only Steam source then explicitly analyzes three existing saved identities',async({browser},testInfo)=>{
 const readOnly=process.env.FMG_ANALYZE_RENDERER_READONLY==='approved';
 test.skip(process.env.FMG_ANALYZE_FROZEN!=='64692'||(!readOnly&&process.env.FMG_ANALYZE_RENDERER!=='approved'),'Root-only execution after frozen source/build and exclusive64692 lease. Explicit readonly or1Steam refresh+3reanalyses.');test.setTimeout(readOnly?90_000:300_000);
 const f=await analyzeFixture('renderer',readOnly);let context:BrowserContext|undefined,page:Page|undefined,server:Server|undefined;
 let pageErrors=0,consoleProblems=0,blockedImages=0,blockedOther=0,unexpectedBridge=0,lastJob:string|undefined;
 const bridge:Record<string,number>={};
 try{
  const game=await f.games.detail(f.ids.game_id),yt=await f.creators.detail(f.ids.youtube_id),x=await f.creators.detail(f.ids.x_id);
  requireCheck(game.source_identity.canonical_url&&yt.source_identity.canonical_url&&x.source_identity.canonical_url,'canonical_sources');
  const actions:Record<string,(v?:any)=>Promise<unknown>>={
   'connection.status':async()=>({serviceUrl:ORIGIN,hasKey:true,storageAvailable:true}),'connection.test':async()=>{await f.library.session();return {authenticated:true,proxy:'system',route:'direct'};},
   'preferences.read':async()=>({appearance:'system',fontSize:'default',automaticUpdates:false}),'updates.status':async()=>({phase:'development',installedVersion:'0.2.0-alpha.1',lastCheckedAt:null,lastAttemptAt:null,release:null,error:null}),
   'library.list':v=>f.library.list(v),'library.detail':v=>f.library.detail(v),'games.list':v=>f.games.list(v),'games.detail':v=>f.games.detail(v),'creators.list':v=>f.creators.list(v),'creators.detail':v=>f.creators.detail(v),'creators.works':v=>f.creators.works(v),'settings.collection':()=>f.settings.collection(),
   'analysis.steamImport':v=>f.analysis.steamImport(v),'analysis.create':async v=>{const result=await f.analysis.create(v);requireCheck(result.outcome==='job','expected_real_job');if(result.outcome==='job')lastJob=result.id;return result;},'analysis.detail':v=>f.analysis.detail(v),'analysis.changed':v=>f.analysis.changed(v),
  };
  server=createServer(async(req,res)=>{const root=ROOT+'/out/renderer',relative=req.url==='/'?'index.html':String(req.url).split('?')[0].replace(/^\/+/,''),file=path.resolve(root,relative);if(req.method!=='GET'||!file.startsWith(root+'/')){res.writeHead(403).end();return;}try{const mime:Record<string,string>={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'};res.writeHead(200,{'Content-Type':mime[path.extname(file)]??'application/octet-stream','Cache-Control':'no-store'});res.end(await readFile(file));}catch{res.writeHead(404).end();}});
  await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  context=await browser.newContext({viewport:{width:1320,height:920},reducedMotion:'reduce'});context.setDefaultTimeout(15_000);
  await context.route('**/*',route=>{const u=route.request().url();if(u.startsWith(origin+'/')||u.startsWith('data:')||u.startsWith('about:'))return route.continue();if(route.request().resourceType()==='image'){blockedImages++;return route.fulfill({status:204,body:''});}blockedOther++;return route.abort();});
  page=await context.newPage();page.on('pageerror',()=>pageErrors++);page.on('console',m=>{if(['error','warning'].includes(m.type()))consoleProblems++;});
  await page.exposeBinding('__fmgInvoke',async(_source,name:string,input:unknown)=>{bridge[name]=(bridge[name]??0)+1;const action=actions[name];if(!action){unexpectedBridge++;return {ok:false,error:{code:'fixture_scope',message:'Outside this verification.',retryable:false}};}return publicResult(()=>action(input));});
  await page.addInitScript(()=>{const group=(name:string,methods:string[])=>Object.fromEntries(methods.map(method=>[method,(input?:unknown)=>(window as any).__fmgInvoke(`${name}.${method}`,input)]));Object.defineProperty(window,'desktop',{configurable:false,value:{
   connection:group('connection',['status','test','save','clear']),preferences:group('preferences',['read','update','restoreAppearance']),updates:group('updates',['status','check']),library:group('library',['list','detail']),games:group('games',['list','detail','create','update']),creators:group('creators',['list','detail','create','update','rebind','works','createWork','updateWork','createContact','updateContact']),settings:group('settings',['collection','connection','setCollection','reanalysis','smtp']),analysis:group('analysis',['steamImport','bindYouTube','create','detail','changed','retry','resume']),match:group('match',['activities']),collaboration:group('collaboration',['creatorHistory']),openExternal:(v:string)=>(window as any).__fmgInvoke('openExternal',v),
  }});});
  await f.checkpoint(readOnly?'readonly_tasks':'steam_source_only');const initialEvents=(await events()).length;await page.goto(origin);await expect(page.getByText('Workspace linked',{exact:true})).toBeVisible();
  if(readOnly){
   await page.getByRole('button',{name:/^Analysis tasks/}).click();const drawer=page.getByRole('dialog',{name:'Analysis',exact:true});const xTask=drawer.locator('.analysis-task').filter({hasText:x.source_identity.canonical_url!}).filter({has:page.getByRole('button',{name:'View profile',exact:true})}).first();await expect(xTask).toBeVisible();await xTask.getByRole('button',{name:'View profile',exact:true}).click();await expect(drawer).toBeHidden();
   const insights=page.getByRole('region',{name:'Analysis insights'});await expect(insights).toBeVisible();await expect(insights.getByText(/21 recent original posts/)).toBeVisible();const evidence=insights.locator('.insight-evidence').first();await evidence.locator('summary').click();await expect(evidence).toHaveAttribute('open','');await expect(evidence.locator('p,li').first()).toBeVisible();
   const evidenceShot=testInfo.outputPath('analysis-readonly-x-evidence.png');await page.screenshot({path:evidenceShot});(f.report.screenshots as string[]).push(evidenceShot);
   await f.checkpoint('readonly_narrow_light');await page.getByRole('button',{name:/^Analysis tasks/}).click();await expect(drawer).toBeVisible();await page.setViewportSize({width:760,height:920});await page.evaluate(()=>{document.documentElement.style.fontSize='135%';});await drawer.getByRole('button',{name:'Close analysis tasks'}).focus();await page.keyboard.press('Tab');requireCheck(await page.evaluate(()=>document.activeElement instanceof HTMLElement&&document.activeElement!==document.body),'keyboard_focus');const layout=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches}));requireCheck(layout.width<=layout.viewport+1&&layout.reduced,'narrow_reduced_layout');const light=testInfo.outputPath('analysis-readonly-light-narrow.png');await page.screenshot({path:light});(f.report.screenshots as string[]).push(light);
   await f.checkpoint('readonly_dark_legibility');await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
   const contrast=await drawer.evaluate(element=>{
    const lum=(color:string)=>{const channels=(color.match(/[\d.]+/g)??[]).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return channels[0]*.2126+channels[1]*.7152+channels[2]*.0722;};
    const ratio=(a:string,b:string)=>{const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);};const pane=getComputedStyle(element),primary=element.querySelector<HTMLButtonElement>('button.primary')!,secondary=element.querySelector<HTMLButtonElement>('.analysis-task button:not(.primary)')!;const a=getComputedStyle(primary),b=getComputedStyle(secondary);return {text:ratio(pane.color,pane.backgroundColor),primary:ratio(a.color,a.backgroundColor),secondary:ratio(b.color,b.backgroundColor),primaryRadius:a.borderRadius,secondaryRadius:b.borderRadius};
   });requireCheck(contrast.text>=4.5&&contrast.primary>=4.5&&contrast.secondary>=4.5&&parseFloat(contrast.primaryRadius)>=8&&parseFloat(contrast.secondaryRadius)>=8,'dark_button_legibility');f.report.dark_contrast=contrast;const dark=testInfo.outputPath('analysis-readonly-dark-narrow.png');await page.screenshot({path:dark});(f.report.screenshots as string[]).push(dark);
   await drawer.getByRole('button',{name:'Close analysis tasks'}).focus();await page.keyboard.press('Escape');await expect(drawer).toBeHidden();requireCheck(f.writes.length===0&&canonical(await eventCounts(initialEvents))===canonical({}),'readonly_zero_posts_or_upstream');requireCheck(!pageErrors&&!consoleProblems&&!unexpectedBridge&&!blockedOther,'renderer_runtime_errors');Object.assign(f.report,{status:'passed',stage:'complete',checks:['get_only_saved_x_history_navigation','21_recent_posts_and_evidence','narrow_135_keyboard_reduced_motion','dark_button_contrast'],native_acceptance:false});
  }else{
  await page.getByRole('tab',{name:'Games',exact:true}).click();
  const games=page.getByRole('tabpanel',{name:'Games',exact:true});await games.getByRole('searchbox',{name:'Search games'}).fill(game.name!);await games.getByRole('button',{name:'Search',exact:true}).click();await games.getByRole('button',{name:`Open ${game.name}`,exact:true}).click();
  await page.getByRole('button',{name:'Refresh Steam source',exact:true}).click();const offset=(await events()).length;f.permitImport();await page.getByRole('button',{name:'Import source',exact:true}).click();await expect(page.getByRole('button',{name:'Analyze game',exact:true})).toBeVisible();
  const imported=await f.games.detail(game.id);requireCheck(imported.id===game.id&&imported.revision===game.revision+1&&imported.last_analyzed_at===game.last_analyzed_at&&imported.next_analysis_at===game.next_analysis_at&&canonical(imported.manual_overrides)===canonical(game.manual_overrides)&&canonical(imported.reference_works)===canonical(game.reference_works)&&imported.favorite===game.favorite,'source_only_preserves_record');requireCheck(canonical(await eventCounts(offset))===canonical({steam:1})&&f.writes.length===1,'source_only_zero_model');
  f.report.source_only={revision_before:game.revision,revision_after:imported.revision,event_counts:await eventCounts(offset),manual_hash:sha(canonical(imported.manual_overrides)),reference_hash:sha(canonical(imported.reference_works))};
  const activePage=page;
  async function analyze(button:string,url:string,id:string,expectedCounts:Record<string,number>,label:string){
   await f.checkpoint(label);const start=(await events()).length;lastJob=undefined;await activePage.getByRole('button',{name:button,exact:true}).click();const drawer=activePage.getByRole('dialog',{name:'Analysis',exact:true});await expect(drawer.getByRole('region',{name:'Confirm analysis'})).toBeVisible();f.permitAnalyze(url);await drawer.getByRole('button',{name:'Analyze now',exact:true}).click();await expect.poll(()=>lastJob,{timeout:25_000}).toBeTruthy();const idOfJob=lastJob!;
   const task=drawer.locator('.analysis-task').filter({hasText:idOfJob});const ready=task.getByRole('button',{name:'View profile',exact:true});const deadline=Date.now()+150_000;while(!(await ready.isVisible())&&Date.now()<deadline){try{await expect(ready).toBeVisible({timeout:10_000});}catch{const refresh=task.getByRole('button',{name:'Refresh status',exact:true});if(await refresh.isVisible()&&await refresh.isEnabled())await refresh.click();}}await expect(ready).toBeVisible();const job=await f.analysis.detail({jobId:idOfJob});requireCheck(job.status==='succeeded'&&job.profile_id===id,'job_same_profile');requireCheck(canonical(await eventCounts(start))===canonical(expectedCounts),'exact_pipeline_counts');
   (f.report.checks as unknown[]).push({label,job_id:job.id,profile_id:job.profile_id,event_counts:await eventCounts(start)});const shot=testInfo.outputPath(label+'.png');await activePage.screenshot({path:shot});(f.report.screenshots as string[]).push(shot);await task.getByRole('button',{name:'View profile',exact:true}).click();await expect(drawer).toBeHidden();
  }
  await analyze('Analyze game',game.source_identity.canonical_url!,game.id,{steam:1,game_extraction:1,game_visual:1,game_synthesis:1,asset_download:1},'game_ready');
  const gameAfter=await f.games.detail(game.id);requireCheck(canonical(gameAfter.manual_overrides)===canonical(game.manual_overrides)&&canonical(gameAfter.reference_works)===canonical(game.reference_works)&&gameAfter.last_analyzed_at!==game.last_analyzed_at,'analyzed_game_preserves_manual');await page.getByText('Game analysis',{exact:true}).click();await expect(page.getByRole('region',{name:'Analysis insights'})).toBeVisible();
  await page.getByRole('tab',{name:'Creators',exact:true}).click();const creators=page.getByRole('tabpanel',{name:'Creators',exact:true});
  async function openCreator(name:string){await creators.getByRole('searchbox',{name:'Search creators'}).fill(name);await creators.getByRole('button',{name:'Search',exact:true}).click();await creators.getByRole('button',{name:`Open ${name}`,exact:true}).click();}
  await openCreator(yt.name!);await analyze('Analyze creator',yt.source_identity.canonical_url!,yt.id,{youtube_channel:1,youtube_playlist:1,youtube_videos:1,creator_map_00:1,creator_map_01:1,creator_visual:1,creator_content:1,creator_presentation:1,creator_performance:1,creator_commercial:1,creator_brief:1,asset_download:2},'youtube_ready');await expect(page.getByRole('region',{name:'Analysis insights'})).toBeVisible();const ytAfter=await f.creators.detail(yt.id);requireCheck(canonical(ytAfter.manual_overrides)===canonical(yt.manual_overrides)&&ytAfter.name===yt.name,'youtube_manual_preserved');
  await page.getByRole('button',{name:'Back to creators',exact:true}).click();await openCreator(x.name!);await analyze('Analyze creator',x.source_identity.canonical_url!,x.id,{x_user:1,x_posts:1,x_map_00:1,x_map_01:1,x_map_02:1,x_final:1},'x_ready');await expect(page.getByText(/21 recent original posts/)).toBeVisible();const xAfter=await f.creators.detail(x.id);requireCheck(canonical(xAfter.manual_overrides)===canonical(x.manual_overrides)&&xAfter.name===x.name,'x_manual_preserved');
  await f.checkpoint('history_narrow_keyboard');await page.getByRole('button',{name:/^Analysis tasks/}).click();const drawer=page.getByRole('dialog',{name:'Analysis',exact:true});await expect(drawer.getByText('Analysis failed',{exact:true}).first()).toBeVisible();requireCheck(!bridge['analysis.retry']&&!bridge['analysis.resume']&&!bridge['analysis.bindYouTube'],'no_unapproved_recovery_or_binding');
  await page.setViewportSize({width:760,height:920});await page.evaluate(()=>{document.documentElement.style.fontSize='135%';});await drawer.getByRole('button',{name:'Close analysis tasks'}).focus();await page.keyboard.press('Tab');requireCheck(await page.evaluate(()=>document.activeElement instanceof HTMLElement&&document.activeElement!==document.body),'keyboard_focus');const layout=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches}));requireCheck(layout.width<=layout.viewport+1&&layout.reduced,'narrow_reduced_layout');const narrow=testInfo.outputPath('analysis-narrow-135.png');await page.screenshot({path:narrow});(f.report.screenshots as string[]).push(narrow);
  await page.keyboard.press('Escape');await expect(drawer).toBeHidden();requireCheck(f.writes.length===4&&f.writes.every(w=>w.status===200||w.status===201),'exact_four_ui_writes');requireCheck(!pageErrors&&!consoleProblems&&!unexpectedBridge&&!blockedOther,'renderer_runtime_errors');Object.assign(f.report,{status:'passed',stage:'complete',first_binding:'not_repeated',fault_recovery:'not_executed',native_acceptance:false});
  }
 }catch(e){f.report.status='failed';f.report.error=e instanceof Error&&/^[a-z0-9_]+$/.test(e.message)?e.message:'ui_assertion_failed';if(e instanceof Error)f.report.locator_failure=e.message.match(/waiting for ([^\n]+)/)?.[1]??null;try{if(page){const screenshot=testInfo.outputPath('analyze-failure.png');await page.screenshot({path:screenshot});(f.report.screenshots as string[]).push(screenshot);}}catch{f.report.failure_screenshot='unavailable';}}
 finally{await context?.close();if(server)await new Promise<void>(resolve=>server!.close(()=>resolve()));Object.assign(f.report,{bridge_counts:bridge,errors:{pageErrors,consoleProblems,unexpectedBridge,blockedOther},external_images_suppressed:blockedImages});await f.finish();}
 requireCheck(f.report.status==='passed','analyze_renderer_failed');
});
